#pragma once

#include <opcuapp/structs.h>

namespace opcua {

OPCUA_DEFINE_ENCODEABLE(ActivateSessionRequest);
OPCUA_DEFINE_ENCODEABLE(ActivateSessionResponse);
OPCUA_DEFINE_ENCODEABLE(BrowseRequest);
OPCUA_DEFINE_ENCODEABLE(BrowseResponse);
OPCUA_DEFINE_ENCODEABLE(CloseSessionRequest);
OPCUA_DEFINE_ENCODEABLE(CloseSessionResponse);
OPCUA_DEFINE_ENCODEABLE(CreateSessionRequest);
OPCUA_DEFINE_ENCODEABLE(CreateSessionResponse);
OPCUA_DEFINE_ENCODEABLE(CreateSubscriptionRequest);
OPCUA_DEFINE_ENCODEABLE(CreateSubscriptionResponse);
OPCUA_DEFINE_ENCODEABLE(CreateMonitoredItemsRequest);
OPCUA_DEFINE_ENCODEABLE(CreateMonitoredItemsResponse);
OPCUA_DEFINE_ENCODEABLE(DeleteMonitoredItemsRequest);
OPCUA_DEFINE_ENCODEABLE(DeleteMonitoredItemsResponse);
OPCUA_DEFINE_ENCODEABLE(DeleteSubscriptionsResponse);
OPCUA_DEFINE_ENCODEABLE(GetEndpointsRequest);
OPCUA_DEFINE_ENCODEABLE(GetEndpointsResponse);
OPCUA_DEFINE_ENCODEABLE(FindServersRequest);
OPCUA_DEFINE_ENCODEABLE(FindServersResponse);
OPCUA_DEFINE_ENCODEABLE(PublishRequest);
OPCUA_DEFINE_ENCODEABLE(PublishResponse);
OPCUA_DEFINE_ENCODEABLE(ReadRequest);
OPCUA_DEFINE_ENCODEABLE(ReadResponse);
OPCUA_DEFINE_ENCODEABLE(WriteRequest);
OPCUA_DEFINE_ENCODEABLE(WriteValue);
OPCUA_DEFINE_ENCODEABLE(WriteResponse);
OPCUA_DEFINE_ENCODEABLE(TranslateBrowsePathsToNodeIdsRequest);
OPCUA_DEFINE_ENCODEABLE(TranslateBrowsePathsToNodeIdsResponse);
OPCUA_DEFINE_ENCODEABLE(AddNodesRequest);
OPCUA_DEFINE_ENCODEABLE(AddNodesItem);
OPCUA_DEFINE_ENCODEABLE(AddNodesResponse);
OPCUA_DEFINE_ENCODEABLE(AddNodesResult);
OPCUA_DEFINE_ENCODEABLE(DeleteNodesRequest);
OPCUA_DEFINE_ENCODEABLE(DeleteNodesItem);
OPCUA_DEFINE_ENCODEABLE(DeleteNodesResponse);
OPCUA_DEFINE_ENCODEABLE(CallRequest);
OPCUA_DEFINE_ENCODEABLE(CallResponse);

}  // namespace opcua
